### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by aleatorictv** [4dsystems/Diablo16-Serial-Arduino-Library#1]
I'm trying to get a uLCD-70DT running in tandem with an Arduino Uno.  I downloaded these libraries, installed them with my other Arduino libraries, opened up the BigDemo.ino and get these errors on compiling with Arduino 1.0.5-r2:

> C:\Users\ariel\Documents\Arduino\libraries\Diablo_Serial_4DLib\Diablo_Serial_4DLib.cpp:1376: error: no 'word Diablo_Serial_4DLib::peekM(word)' member function declared in class 'Diablo_Serial_4DLib'
> C:\Users\ariel\Documents\Arduino\libraries\Diablo_Serial_4DLib\Diablo_Serial_4DLib.cpp:1423: error: no 'void Diablo_Serial_4DLib::pokeM(word, word)' member function declared in class 'Diablo_Serial_4DLib'

peekM() and pokeM() don't seem to be listed in the header file

**Comment by 4dsystems** [comment]
Thank you for reporting this.
The updated .h file has been uploaded. Please try again.
Regards
4D Systems
